### ISSUE TITLE
need data export

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactory-games#1]
We will need a data structure to hold data as game progresses, which can eventually be used to deploy at expfactory.org
- step 1: local export of data from data structure upon completion of game
- step 2: integration with expfactory.org (meaning the expfactory.js object that uses backbone.js)

**Comment by vsoch** [comment]
will close https://github.com/expfactory/expfactory-python/issues/91

**Comment by jonathanicholas** [comment]
so I believe this is ready to be hooked up with expfactory. There are two steps here:
1) On each trial, data is sent to the [ save](https://github.com/expfactory/expfactory-games/blob/master/bridge_game_static/static/games/bridge_game/Run.js#L384) function in Run.js. We should make this function a standard for all games. Save then calls the input/sendData functions in..

2) [saver.js](https://github.com/expfactory/expfactory-games/blob/master/bridge_game_static/static/games/bridge_game/saver.js) which creates a dict from the data and then gives it to expfactory.js. This file is necessary because of the way Phaser handles states. We can't send data back to our template.html (which would be preferable) because it initializes the game state and communication is one-directional unless we utilize local memory, but this wouldn't update on a trial-by-trial basis. So saver exists outside of the state changes and can pass our data to expfactory.

Let me know if this setup won't work; it's pretty similar to what we were doing before but with the expfactory object added in. The main thing is just that it will require saver.js to be an additional dependency for every game.

**Comment by vsoch** [comment]
This looks great! The save function would be detailed in docs to make new games, and saver looks like it can be a standard django template. Is the idea that we just need saver.js embedded in the document on ready function before the game is defined?

I finished most of thesis stuffs  yesterday - I need to read it through once more before sending out to committee, but I'll definitely be able to work on this soon. I'm pretty excited about it. :)

**Comment by jonathanicholas** [comment]
Yep! Just need it defined before Run.js.

And congrats! You're so close :smile:

**Comment by vsoch** [comment]
@boomsbloom I'm almost finished getting games integrated - the last thing I need is some kind of variable in the trial (or somewhere) to indicate that the experiment is finished, that way I can notify the server to respond with a redirect to the next experiment (instead of just sending data back).

**Comment by jonathanicholas** [comment]
should be able to work on this in like an hour. Ended up having to spend a
bunch of time yesterday/this morning on a different project but almost
finished there

**Comment by vsoch** [comment]
ok, awesome! Yeah I think we are going to have these up and running on mturk really soon :)  And no rush, it's Friday! :D

**Comment by vsoch** [comment]
This is finished, will need testing, but closing issue!
