### ISSUE TITLE
running games throws 500 Error

### ISSUE THREAD

**Issue by jonathanicholas** [expfactory/expfactory-games#11]
```
 Failed to load resource: the server responded with a status of 500 (OK)
```

Occurs for all games in preview and also when a battery is deployed. As far as I can tell this is isolated only for games.

**Comment by vsoch** [comment]
@rwblair has taken over development for expfactory since I'm transitioning to a new job - I'm going to be working on a "version 2.0" of expfactory that is simplified (mturk removed and modular) but to have this fix immediately you should work with him - likely its an oversight that wasn't tested with his last push to updates. Do you want to open the issue on expfactory-docker?

**Comment by rwblair** [comment]
Sorry about the delay on this. The templates for games appear to be missing on the server. I updated the game templates through the website (Experiments -> Installed Experiments) using the button between the preview and delete buttons. The previews worked for me after I did this. @boomsbloom can you confirm that they are working for you now?

**Comment by jonathanicholas** [comment]
Works now! Thanks.
